INSERT INTO AUTHOR (FIRSTNAME, LASTNAME)
VALUES ('Stephen', 'King');

INSERT INTO GENRE (GENRE)
VALUES ('Dark Fantasy');

INSERT INTO BOOK (TITLE, AUTHOR_ID, GENRE_ID)
VALUES ('The Green Mile', 1, 1);