INSERT INTO AUTHOR (ID, FIRSTNAME, LASTNAME)
VALUES (1, 'Stephen', 'King');

INSERT INTO GENRE (ID, GENRE)
VALUES (1, 'Dark Fantasy');

INSERT INTO BOOK (TITLE, AUTHOR_FK, GENRE_FK)
VALUES ('The Green Mile', 1, 1);