INSERT INTO AUTHOR (ID, FIRSTNAME, LASTNAME)
VALUES (AUTHOR_SEQUENCE.NEXTVAL, 'Stephen', 'King');

INSERT INTO GENRE (ID, GENRE)
VALUES (GENRE_SEQUENCE.NEXTVAL, 'Dark Fantasy');

INSERT INTO BOOK (ID, TITLE, AUTHOR_ID, GENRE_ID)
VALUES (BOOK_SEQUENCE.NEXTVAL, 'The Green Mile', 1, 1);