-- drop all tables to start from the scratch each time
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS BOOK;

-- create required tables
CREATE TABLE AUTHOR
(
  ID        BIGINT AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255) NOT NULL,
  LASTNAME  VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE GENRE
(
  ID    BIGINT AUTO_INCREMENT,
  GENRE VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY(ID)
);

CREATE TABLE BOOK
(
  ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
  TITLE     VARCHAR(255) NOT NULL,
  AUTHOR_FK BIGINT,
  GENRE_FK  BIGINT,
  PRIMARY KEY(ID),
  FOREIGN KEY (AUTHOR_FK) REFERENCES AUTHOR (ID),
  FOREIGN KEY (GENRE_FK) REFERENCES GENRE (ID)
);

CREATE UNIQUE INDEX UNIQUE_AUTHOR ON AUTHOR (FIRSTNAME, LASTNAME);
CREATE UNIQUE INDEX UNIQUE_BOOK ON BOOK (TITLE, AUTHOR_FK);