-- drop all tables to start from the scratch each time
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS BOOK;

DROP SEQUENCE IF EXISTS GENRE_SEQUENCE;
DROP SEQUENCE IF EXISTS AUTHOR_SEQUENCE;
DROP SEQUENCE IF EXISTS BOOK_SEQUENCE;

-- create required tables
CREATE TABLE AUTHOR
(
  ID        BIGINT,
  FIRSTNAME VARCHAR(255) NOT NULL,
  LASTNAME  VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE GENRE
(
  ID    BIGINT,
  GENRE VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY(ID)
);

CREATE TABLE BOOK
(
  ID        BIGINT PRIMARY KEY,
  TITLE     VARCHAR(255) NOT NULL,
  AUTHOR_ID BIGINT,
  GENRE_ID  BIGINT,
  PRIMARY KEY(ID),
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID),
  FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID)
);

CREATE UNIQUE INDEX UNIQUE_AUTHOR ON AUTHOR (FIRSTNAME, LASTNAME);
CREATE UNIQUE INDEX UNIQUE_BOOK ON BOOK (TITLE, AUTHOR_ID);

CREATE SEQUENCE GENRE_SEQUENCE MINVALUE 1 INCREMENT BY 50 CACHE 100;
CREATE SEQUENCE AUTHOR_SEQUENCE MINVALUE 1 INCREMENT BY 50 CACHE 100;
CREATE SEQUENCE BOOK_SEQUENCE MINVALUE 1 INCREMENT BY 50 CACHE 100;