-- drop all tables to start from the scratch each time
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS BOOK;

-- create required tables
CREATE TABLE AUTHOR
(
  ID         INT PRIMARY KEY AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255),
  LASTNAME  VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE GENRE
(
  ID    INT PRIMARY KEY AUTO_INCREMENT,
  GENRE VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE BOOK
(
  ID        INT PRIMARY KEY AUTO_INCREMENT,
  TITLE     VARCHAR(255),
  AUTHOR_ID INT,
  GENRE_ID  INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID),
  FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID)
);