INSERT INTO AUTHOR (ID, FIRSTNAME, LASTNAME)
VALUES (AUTHOR_SEQUENCE.NEXTVAL, 'test db first name', 'test db last name');

INSERT INTO GENRE (ID, GENRE)
VALUES (GENRE_SEQUENCE.NEXTVAL, 'test db genre');

INSERT INTO BOOK (ID, TITLE, AUTHOR_ID, GENRE_ID)
VALUES (BOOK_SEQUENCE.NEXTVAL, 'test db title', 1, 1);