INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME)
VALUES (AUTHOR_SEQUENCE.NEXTVAL, 'test db first name', 'test db last name');

INSERT INTO GENRE (ID, GENRE)
VALUES (GENRE_SEQUENCE.NEXTVAL, 'test db genre');

INSERT INTO BOOK (ID, TITLE)
VALUES (BOOK_SEQUENCE.NEXTVAL, 'test db title');

INSERT INTO MAP_BOOK_AUTHOR (BOOK_ID, AUTHOR_ID)
VALUES (1, 1);

INSERT INTO MAP_BOOK_GENRE (BOOK_ID, GENRE_ID)
VALUES (1, 1);

INSERT INTO REVIEW (ID, REVIEW_TEXT, BOOK_ID)
VALUES (REVIEW_SEQUENCE.NEXTVAL, 'test db review', 1);